name: fast-kickstart-crud
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.1
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - click=8.0.4
  - colorama=0.4.6
  - exceptiongroup=1.1.2
  - fastapi=0.100.0
  - h11=0.12.0
  - idna=3.4
  - libffi=3.4.4
  - openssl=3.0.9
  - pip=23.1.2
  - pydantic=1.10.8
  - python=3.10.12
  - setuptools=67.8.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - starlette=0.27.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uvicorn=0.20.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
